# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

linters:
  disable:
    - errcheck # Currently too many places are ignoring errors
  enable:
    - nolintlint
linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA9003' # Flags empty else{}, which is sometimes useful for a comment.
      - '-SA1019' # disable noisy deprecated API checks; TODO: fix and re-enable
