// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package sim

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/weaver/internal/sim/swapper",
		Iface: reflect.TypeOf((*swapper)(nil)).Elem(),
		Impl:  reflect.TypeOf(swapperImpl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return swapper_local_stub{impl: impl.(swapper), tracer: tracer, swapMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/weaver/internal/sim/swapper", Method: "Swap", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return swapper_client_stub{stub: stub, swapMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/weaver/internal/sim/swapper", Method: "Swap", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return swapper_server_stub{impl: impl.(swapper), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return swapper_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[swapper] = (*swapperImpl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*swapperImpl)(nil)

// Local stub implementations.

type swapper_local_stub struct {
	impl        swapper
	tracer      trace.Tracer
	swapMetrics *codegen.MethodMetrics
}

// Check that swapper_local_stub implements the swapper interface.
var _ swapper = (*swapper_local_stub)(nil)

func (s swapper_local_stub) Swap(ctx context.Context, a0 int, a1 int) (r0 int, r1 int, err error) {
	// Update metrics.
	begin := s.swapMetrics.Begin()
	defer func() { s.swapMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "sim.swapper.Swap", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Swap(ctx, a0, a1)
}

// Client stub implementations.

type swapper_client_stub struct {
	stub        codegen.Stub
	swapMetrics *codegen.MethodMetrics
}

// Check that swapper_client_stub implements the swapper interface.
var _ swapper = (*swapper_client_stub)(nil)

func (s swapper_client_stub) Swap(ctx context.Context, a0 int, a1 int) (r0 int, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.swapMetrics.Begin()
	defer func() { s.swapMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "sim.swapper.Swap", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	enc.Int(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Int()
	r1 = dec.Int()
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.20.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type swapper_server_stub struct {
	impl    swapper
	addLoad func(key uint64, load float64)
}

// Check that swapper_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*swapper_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s swapper_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Swap":
		return s.swap
	default:
		return nil
	}
}

func (s swapper_server_stub) swap(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()
	var a1 int
	a1 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.Swap(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Int(r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type swapper_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that swapper_reflect_stub implements the swapper interface.
var _ swapper = (*swapper_reflect_stub)(nil)

func (s swapper_reflect_stub) Swap(ctx context.Context, a0 int, a1 int) (r0 int, r1 int, err error) {
	err = s.caller("Swap", ctx, []any{a0, a1}, []any{&r0, &r1})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*swapperError)(nil)

type __is_swapperError[T ~struct{ weaver.AutoMarshal }] struct{}

var _ __is_swapperError[swapperError]

func (x *swapperError) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("swapperError.WeaverMarshal: nil receiver"))
	}
}

func (x *swapperError) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("swapperError.WeaverUnmarshal: nil receiver"))
	}
}
func init() { codegen.RegisterSerializable[*swapperError]() }
