[serviceweaver]
binary = "./collatz"
rollout = "5m"

[[serviceweaver.colocate]]
name = "all"
components = [
    "github.com/ServiceWeaver/weaver/Main",
    "github.com/ServiceWeaver/weaver/examples/collatz/Even",
    "github.com/ServiceWeaver/weaver/examples/collatz/Odd"
]

[ssh]
locations = "./ssh_locations.txt"

[gke]
regions = ["us-west1"]
listeners.collatz = {public_hostname = "collatz.example.com"}
