[serviceweaver]
binary = "./onlineboutique"
rollout = "5m"

[single]
listeners.boutique = {address = "localhost:12345"}

[multi]
listeners.boutique = {address = "localhost:12345"}

[gke]
regions = ["us-west1"]
listeners.boutique = {public_hostname = "onlineboutique.example.com"}
