id = "v1"

[nodes.main]
address = "localhost:9000"
components = ["github.com/ServiceWeaver/weaver/Main"]
listeners = {collatz = "localhost:8000"}

[nodes.odd]
address = "localhost:9001"
components = ["github.com/ServiceWeaver/weaver/examples/collatz/Odd"]

[nodes.even]
address = "localhost:9002"
components = ["github.com/ServiceWeaver/weaver/examples/collatz/Even"]
