[serviceweaver]
binary = "./factors"
rollout = "5m"

[listeners]
factors = {local_address = "localhost:9000"}

[gke]
regions = ["us-west1"]
public_listener = [
  {name = "factors", hostname = "factors.example.com"},
]
