[serviceweaver]
binary = "./factors"
rollout = "5m"

[single]
listeners.factors = {address = "localhost:9000"}

[multi]
listeners.factors = {address = "localhost:9000"}

[gke]
regions = ["us-west1"]
listeners.factors = {is_public = true, hostname = "factors.example.com"}
