[serviceweaver]
binary = "./chat"
rollout = "5m"

[single]
listeners.chat = {address = "localhost:9000"}

[multi]
listeners.chat = {address = "localhost:9000"}

[gke]
regions = ["us-west1", "us-east1"]
listeners.chat = {public_hostname = "chat.example.com"}

["github.com/ServiceWeaver/weaver/examples/chat/SQLStore"]
db_driver = "mysql"
db_uri = "root:@tcp(localhost:3306)/"
