[serviceweaver]
binary = "./chat"
rollout = "5m"

[single]
listeners.chat = {address = "localhost:9000"}

[multi]
listeners.chat = {address = "localhost:9000"}

[gke]
regions = ["us-west1", "us-east1"]
listeners.chat = {public_hostname = "chat.example.com"}

[kube]
listeners.chat = {public = true}
# To upload the image to another repository, check `weaver kube deploy -h`.
repo = "docker.io/my_docker_hub_username/"

["github.com/ServiceWeaver/weaver/examples/chat/SQLStore"]
db_driver = "mysql"
db_uri = "root:password@tcp(localhost:3306)/chat"
