[serviceweaver]
binary = "./reverser"
rollout = "5m"

[listeners]
reverser = {local_address = ":9000"}

[gke]
regions = ["us-west1"]
public_listener = [
  {name = "reverser", hostname = "reverser.example.com"},
]
