[serviceweaver]
binary = "./reverser"
rollout = "5m"

[single]
listeners.reverser = {address = "localhost:9000"}

[multi]
listeners.reverser = {address = "localhost:9000"}

[gke]
regions = ["us-west1"]
# TODO(spetrovic): Rewrite to match the single/multi listeners format.
public_listener = [
  {name = "reverser", hostname = "reverser.example.com"},
]
